name: clean_features
description: A clean architecture implementation for Flutter.
version: 1.0.0
repository: https://github.com/zeroinlee/clean_features

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
